require 'yaml'

VAGRANTFILE_API_VERSION = "2"
DDB_CONFIG_PATH = File.expand_path(File.dirname(__FILE__)) + "/../config.yml"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  ddb_config = YAML.load_file(DDB_CONFIG_PATH)

  config.vm.box = "precise64"
  config.vm.provider 'virtualbox' do |v|
    v.memory = ddb_config["memory"]
    v.cpus = ddb_config["cpus"]
  end

  config.vm.provision "shell",
    inline: "echo 'DOCKER_OPTS=\"-H 0.0.0.0:4243 -H unix:///var/run/docker.sock\"' >> /etc/default/docker"

  config.vm.provision :shell, :path => "bootstrap.sh"

  config.vm.provision "docker"

  ddb_config["services"].each do |service, service_config|
    if service_config["forwarded_ports"]
      config.vm.network "forwarded_port", guest: service_config["forwarded_ports"]["guest"], host: service_config["forwarded_ports"]["guest"]
    end
  end

  config.vm.network "forwarded_port", guest: 4243, host: 4243

  config.vm.synced_folder "../src/", "/home/vagrant/src"

end
